#!/bin/sh

# ----------------------------------------------------------------------
# Nightly rebuild -- Regenerate the list of events every day
# Assumes it's being run such that ./src is the source templates
# ----------------------------------------------------------------------

PATH=/usr/local/bin:/usr/bin:/bin
export PATH

PUBLIST="index.php events/index.php events/events.atom"

if [ -d "src" ] && [ -d "data" ]
then

    if [ -r "create-events-data" ]
    then
        perl create-events-data > data/events.csv
        git commit -m'Updated event data.' data/events.csv
    fi

    for pubfile in $PUBLIST
    do
        touch "src/$pubfile"
        /bin/sh ./build
        /bin/sh ./publish "html/$pubfile"
    done
else
    echo "I don't seem to be in the root of the checkout."
    exit 1
fi
